name: ci

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        context: 
          - architecture: arm64
            qemu: qemu-aarch64-static
            version: '20.04'
            release: focal
          - architecture: armhf
            qemu: qemu-arm-static
            version: '20.04'
            release: focal
          - architecture: x86_64
            version: '20.04'
            release: focal
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Calculate name
        id: image_version
        run: echo "value=${IMAGE_VERSION//./}" >> $GITHUB_OUTPUT
        env:
          IMAGE_VERSION: ${{ matrix.context.version }}
      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/amyspark/appimage${{ steps.image_version.outputs.value }}
          tags: |
            type=raw,value=${{ matrix.context.architecture }}-latest
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/${{ matrix.context.architecture }}
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          build-args: |
            BUILD_REF=${{ github.ref }}
            BUILD_DATE=${{ steps.date.outputs.date }}
            ARCH=${{ matrix.context.architecture }}
            VERSION=${{ matrix.context.version }}
            UBUNTU_RELEASE=${{ matrix.context.release }}
            QEMU_EXECUTABLE=${{ matrix.context.qemu }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
